### ISSUE TITLE
Wireframe - ListChat

### ISSUE THREAD

**Issue by quimpm** [commed-it/web-client#11]
# ListChat
A screen of ListChat must be done in AdobeXD.
## What has to be done
The screen is specified in the state diagram image below.
![State Diagram](https://raw.githubusercontent.com/commed-it/docs/main/17-nov/img/stateapp.png)
* A list of chats like Whatsapp, Telegram...
* The user can search for a chat
* The user can press a chat and the conversation screen will be opened
* In each item, the product only shows an small image if it has, the name, the owner, and the last message.
---
ListChat --> ConversationScreen : Press a conversation

**Comment by Oriolac** [comment]
![chat](https://user-images.githubusercontent.com/23151284/140607871-3c9171bf-e1e1-439c-97db-e32058403746.jpg)
