### ISSUE TITLE
Wireframe - MainScreen Registered

### ISSUE THREAD

**Issue by Emina33** [commed-it/web-client#12]
# Main Screen
The Main Screen of a logged user must be done in JustInMind.
## What has to be done
The screen is specified in the state diagram image below.
![State Diagram](https://raw.githubusercontent.com/commed-it/docs/main/17-nov/img/stateapp.png)
* The user must search and see publications
* The user can press a publication.
* The user can press the button of their profile.
* The down-menu is able as the user has already logged in
---
* MainScreen --> Profile : Press the button of user's profile
* MainScreen --> Chat : Chat button from down-menu.
* MainScreen --> FormalOffer : FormalOffer button from down-menu.
* MainScreen --> PublicationDetail : Press a publication

**Comment by Oriolac** [comment]
![mainscreenregistere](https://user-images.githubusercontent.com/23151284/140608064-3946d309-e0ac-4217-8b97-f8b6e8643017.jpg)
Same refers to #6 :
![mainscreen](https://user-images.githubusercontent.com/23151284/140608066-4a3119ed-c2f0-4502-96a8-f8d5439376b3.jpg)
