### ISSUE TITLE
Implementation of Enterprise Detail

### ISSUE THREAD

**Issue by quimpm** [commed-it/web-client#19]
# Screen Enterprise Detail
## Detailed Description and Context

A screen of Enterprise Profile must be done in react. This screen must show all the information of the Enterprise. Also, this screen will have a tab for seeing the products and services that this enterprise offers.

If the profile owner is registered and on the screen will be able to press a button for editing the profile.

### Endpoints that must be called
- /enterprise/{id}/

## Related Wireframe Issues
- Enterprise Detail

**Comment by Oriolac** [comment]
Related issues:
#1 #22 #20
