### ISSUE TITLE
Implementation of Enterprise Edit

### ISSUE THREAD

**Issue by quimpm** [commed-it/web-client#20]
# Screen Enterprise Edit
## Detailed Description and Context

A screen of Enterprise Edit must be done in react. This screen will have a form in wich we will be able to modify things of our enterprise profile.

### Endpoints that must be called
- /enterprise/{id}/ 

## Related Wireframe Issues
-  Enterpraise Detail

**Comment by Oriolac** [comment]
Related issues
#1 #14
