### ISSUE TITLE
Implementation of Formal Offer List

### ISSUE THREAD

**Issue by quimpm** [commed-it/web-client#25]
# Screen Formal Offer List
## Detailed Description and Context

A screen of the Formal Offer List must be done in react. This has to be done inside Profile screen. It has to have a list of all formal offers with the state of those ones. Also the generated contract should be downloaded form here. This will be only shown to the registered user. 

### Endpoints that must be called
- /formal_offer/{user_id}

## Related Wireframe Issues
- Formal Offer List

**Comment by Oriolac** [comment]
Related issues:
#4 #5 and #3.
