### ISSUE TITLE
Implementation of Formal Offer Form

### ISSUE THREAD

**Issue by quimpm** [commed-it/web-client#27]
# Screen Formal Offer Form
## Detailed Description and Context

A screen of Formal Offer Form must be done in react. In this screen we will provide a form that has to be fulfilled in other to generate and send a formal offer to a client within a chat.

### Endpoints that must be called
- /offer/formaloffer

## Related Wireframe Issues
-

**Comment by Oriolac** [comment]
Related issues:
#4 #3
