### ISSUE TITLE
Wireframe - FormalOfferDetail

### ISSUE THREAD

**Issue by quimpm** [commed-it/web-client#3]
# FormalOfferDetail
A screen of FormalOfferDetail must be done in JustInMind.
## What has to be done
The screen is specified in the state diagram image below.
![State Diagram](https://raw.githubusercontent.com/commed-it/docs/main/17-nov/img/stateapp.png)
It must show:
* The name of the owner of the product/service which has started the interaction.
* The version of the formal offer
* The contract TextField
* The pdf attachment.
---
* FormalOfferDetail --> ListFormalOffer : Go Back
* FormalOffer -right-> Chat : Chat button from down-menu.

**Comment by Oriolac** [comment]
![formalofferdetail](https://user-images.githubusercontent.com/23151284/140607485-58e69ec9-a070-4a7f-a838-df35802bb787.jpg)

**Comment by Oriolac** [comment]
That wireframe screen is a form to the formal offer.

**Comment by Oriolac** [comment]
To sig
![FormalOfferSign](https://user-images.githubusercontent.com/23151284/140607536-e373262f-ee8e-470c-9803-888e07885f77.jpg)
n:
