### ISSUE TITLE
Wireframe - Not Registered Main Screen

### ISSUE THREAD

**Issue by Emina33** [commed-it/web-client#6]
# Not Registered Main Screen
A screen of Not Registered Main Screen must be done in JustInMind.
## What has to be done
The screen is specified in the state diagram image below.
![State Diagram](https://raw.githubusercontent.com/commed-it/docs/main/17-nov/img/stateapp.png)
- The user must search and see publications
- The user can press a publication.
- The user can press the button to log in and register
- The down-menu is disabled as the user is not already logged in.
----
* initialNotRegistered --> login : Press button of the image profile
* initialNotRegistered --> PublicationDetail : Press a publication

**Comment by Oriolac** [comment]
![mainscreen](https://user-images.githubusercontent.com/23151284/140608039-ad180f7b-ad1d-485a-9b09-ed4ffb42501c.jpg)
