### ISSUE TITLE
Wireframe - ConversationScreen

### ISSUE THREAD

**Issue by quimpm** [commed-it/web-client#7]
# ConversationScreen
A screen of ConversationScreen must be done in AdobeXD.
## What has to be done
The screen is specified in the state diagram image below.
![State Diagram](https://raw.githubusercontent.com/commed-it/docs/main/17-nov/img/stateapp.png)
* Can send messages to another user
---
* ConversationScreen -left-> ListChat : Go Back
* ConversationScreen -left-> Profile : Go to the other user profile

**Comment by Oriolac** [comment]
The same as #11 

![chat](https://user-images.githubusercontent.com/23151284/140607878-e774af82-c5c2-4f0e-a9aa-4306462cadd8.jpg)
