### ISSUE TITLE
Wireframe - Bad Login State

### ISSUE THREAD

**Issue by Emina33** [commed-it/web-client#9]
# Screen
A screen of Bad Login State must be done in JustInMind.
## What has to be done
The screen is specified in the state diagram image below.
![State Diagram](https://raw.githubusercontent.com/commed-it/docs/main/17-nov/img/stateapp.png)
### Where is it from?
* login -> bad_login : User or Password are incorrect.
### Description
* The user can press a button to go to register page if it is not already registered.
* The user put the username and password to enter
---
* bad_login --> initialNotRegistered : Go Back button
* bad_login --> RegisterScreen : Press button/link for registration

**Comment by Oriolac** [comment]
Same as #8 but with an error label
![login](https://user-images.githubusercontent.com/23151284/140608155-c79a464d-d80b-4c7e-806e-336fe65120f9.jpg)
